### ISSUE TITLE
having an empty generate object available that can be customized in the generator

### ISSUE THREAD

**Issue by encodeering** [revolut-engineering/jooq-plugin#6]
Hi, what do you think about adding `org.jooq.meta.jaxb.Generate ()` to the pre-configured set of domain object, even if you don't do anything with it.

It would make the configuration on client side look a bit more consistent. 

https://github.com/revolut-engineering/jooq-plugin/blob/af3dabcd4843dc5c5034d6cfa21cf12621cc4510/src/main/kotlin/com/revolut/jooq/GenerateJooqClassesTask.kt#L179

```
        customizeGenerator {
            withGenerate (org.jooq.meta.jaxb.Generate().withXXX ())
            database.withXXX ()
        }
```

Cheers

**Comment by adrianskrobaczrevolut** [comment]
Hello @encodeering 🙂 
Sorry for late response. May I ask what is your use case 🙂 ? I'm asking because the generator passed to the lambda is already preconfigured(you may still modify it as you please), but cannot imagine why you would need to build it from scratch 🤔

**Comment by encodeering** [comment]
Hi @adrianskrobaczrevolut,

we are running version `0.3.2` and need to change a property for jooq that is part of the `Generate ()` context, as a default has changed when migrating jooq from 3.12 to 3.13.

The second code snippet is what we are currently doing and I was wondering whether it would make sense to create an empty `Generate ()` instance somewhere in the method starting on `L179`, as we are seeing a NPE otherwise.

Like

```
Generator()
    .withGenerate(Generate())
    .withName(JavaGenerator::class.qualifiedName)
    ...
```

to customize it with 

```
        customizeGenerator {
            generate.withXXX ()
            database.withXXX ()
        }
```

Cheers

**Comment by adrianskrobaczrevolut** [comment]
Ow, I see I confused the `Generator` with `Generate` 😅 Now I get you and it makes a lot of sense 👍 I'll add it next release and keep you updated here 🙂

**Comment by adrianskrobaczrevolut** [comment]
@encodeering added in the latest release `0.3.4` 🙂

**Comment by encodeering** [comment]
@adrianskrobaczrevolut very cool, just updated the version and it works great
