### ISSUE TITLE
ForcedType not found in Groovy dialect

### ISSUE THREAD

**Issue by hovinen** [revolut-engineering/jooq-plugin#7]
I'm trying to add a custom type converter as indicated in the README but have run in to a problem.

My build.gradle looks like the following:

```
plugins {
    id "com.revolut.jooq-docker" version "0.3.3"
}
...
tasks {
    generateJooqClasses {
        customizeGenerator {
            database.withForcedTypes(
                ForcedType()
                    .withUserType("java.time.Instant")
                    .withConverter("...TimestampConverter")
                    .withTypes("TIMESTAMP( WITHOUT TIME ZONE)?")
            )
        }
    }
}
```

When I attempt to run the generate task, I get the following error:

```
No signature of method: build_3hd7l9zm5ag6m21i0yljprvyg$_run_closure10$_closure23$_closure24.ForcedType() is applicable for argument types: () values: []
```

Thus it does not find `ForcedType`.

How do I get this to work?

Please note that switching to the Kotlin dialect is infeasible in my case for the time being.

**Comment by adrianskrobaczrevolut** [comment]
Hey @hovinen 
Actually examples are written for Kotlin DSL, so what you are missing is the `new` keyword 🙂, also the example is missing the required import. I'll update the examples, but basically it should look like this for Groovy:
```
import org.jooq.meta.jaxb.ForcedType

plugins {
    id "com.revolut.jooq-docker" version "0.3.3"
}
...
tasks {
    generateJooqClasses {
        customizeGenerator {
            database.withForcedTypes(
                new ForcedType()
                    .withUserType("java.time.Instant")
                    .withConverter("...TimestampConverter")
                    .withTypes("TIMESTAMP( WITHOUT TIME ZONE)?")
            )
        }
    }
}
```

**Comment by hovinen** [comment]
That works, thanks!

It might helpful to add Groovy-based examples to the README, since it's not always obvious how one translates the Kotlin examples.
